//
//  ProductDetailPresenter.swift
//  CleanSwiftApp
//
//  Created by Benjoe Vidal on 8/7/20.
//  Copyright (c) 2020 BRV. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProductDetailPresentationLogic
{
  func presentProduct(response: ProductEntity.Response)
}

class ProductDetailPresenter: ProductDetailPresentationLogic
{
  
  weak var viewController: ProductDetailDisplayLogic?
  
  // MARK: Do something
  
    func presentProduct(response: ProductEntity.Response)
  {
    viewController?.displayProductDetails(viewModel: response)
  }
}
