//
//  LoginRouter.swift
//  CleanSwiftApp
//
//  Created by Benjoe Vidal on 8/7/20.
//  Copyright (c) 2020 BRV. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol LoginRoutingLogic
{
  func routeToProductList(segue: UIStoryboardSegue?)
}

protocol LoginDataPassing
{
//  var dataStore: LoginDataStore? { get }
}

class LoginRouter: NSObject, LoginRoutingLogic, LoginDataPassing
{
  weak var viewController: LoginViewController?
//  var dataStore: LoginDataStore?
  
  // MARK: Routing
  
  func routeToProductList(segue: UIStoryboardSegue?)
  {
   
      let storyboard = UIStoryboard(name: "Main", bundle: nil)
      let destinationVC = storyboard.instantiateViewController(withIdentifier: "ProductListViewController") as! ProductListViewController
      navigateToProductList(source: viewController!, destination: destinationVC)
    
  }

  // MARK: Navigation
  
  func navigateToProductList(source: LoginViewController, destination: ProductListViewController)
  {
    source.show(destination, sender: nil)
  }
  
}
